# Use the official Node.js 14 as a parent image
FROM node:16

# Set the working directory
WORKDIR /usr/src/app

# Set working directory
WORKDIR /usr/src/app/backend

# Copy the rest of the application
COPY backend/ .

# Install Node.js dependencies
RUN npm install

# Expose the port the app runs on
EXPOSE 3001

# Run the app
CMD ["node", "app.js"]
