name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Backend Unit Tests
        run: |
          cd backend
          npm install
          npm test

      - name: Frontend Unit Tests
        run: |
          cd frontend
          npm install
          npm test
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Backend Build
        run: |
          cd backend
          npm install
          npm run build

      - name: Frontend Build
        run: |
          cd frontend
          npm install
          npm run build
